version: "3.9"
services:
  typical-chat:
    build: .
    ports:
      - "5173:5173"
  rethinkdb:
    image: "rethinkdb:latest"
    ports:
      - "8181:8080"
      - "48015:28015"
    volumes:
      - data:/data
  redis:
    image: redis
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - cache:/data

volumes:
  data:
    driver: local
  cache:
    driver: local
