FROM node:14 as builder

ENV NODE_ENV=development

WORKDIR /home/typical-chat

COPY package.json yarn.lock ./
RUN yarn
COPY . .

EXPOSE 5173
EXPOSE 8181
EXPOSE 48015
EXPOSE 6379
EXPOSE 6939

CMD ["yarn", "dev"]