version: "3.9"
services:
  typical-chat:
    build: .
    ports:
      - "5173:5173"
  mongo:
    image: mongo
    container_name: monogodb
    ports:
      - "6939:27017"
    volumes:
      - mongodb:/data/db
    env_file: api/.env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  redis:
    image: "redis/redis-stack"
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  mongodb:
    driver: local
  cache:
    driver: local
